In [45]:
import dask.dataframe as dd
import pandas as pd
import numpy as np

In [ ]:
pdf = pd.read_csv("timeseries.csv", dtype={'name':str,'level':str,'city':object,'county':str,'state':str,'country':str,'population':np.float64,'lat':float,'long':float,'url':str,'aggregate':object,'tz':str,'cases':np.float64,'deaths':np.float64,'recovered':np.float64,'active':np.float64,'tested':np.float64,'hospitalized':np.float64,'hospitalized_current':np.float64,'discharged':np.float64,'icu':np.float64,'icu_current':np.float64,'growthFactor':np.float64,'date':object})
df = dd.from_pandas(pdf)

filtered_df = df.query("country == 'Belgium'")
filtered_df = filtered_df.groupby("state").count()
filtered_df.compute()

,name,level,city,county,country,population,lat,long,url,aggregate,...,recovered,active,tested,hospitalized,hospitalized_current,discharged,icu,icu_current,growthFactor,date
state,,,,,,,,,,,,,,,,,,,,,
Brussels-Capital,332,332,0,166,332,332,332,332,332,0,...,0,0,0,0,220,226,0,0,330,332
Flanders,957,957,0,791,957,957,957,957,957,0,...,0,0,0,0,508,675,0,0,951,957
Wallonia,786,786,0,620,786,786,786,786,786,0,...,0,0,0,0,322,561,0,0,781,786

In [ ]:
new_column_df = df.query("country == 'Jamaica'")\
    .assign(seen=lambda x: x.recovered + x.active)
new_column_df.compute()

,name,level,city,county,state,country,population,lat,long,url,...,active,tested,hospitalized,hospitalized_current,discharged,icu,icu_current,growthFactor,date,seen
350240,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-11,NaN
350241,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2020-03-12,NaN
350242,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,4.00,2020-03-13,NaN
350243,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2020-03-14,NaN
350244,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,1.25,2020-03-15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350352,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,142.0,NaN,NaN,NaN,NaN,NaN,NaN,1.01,2020-07-01,697.0
350353,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,145.0,NaN,NaN,NaN,NaN,NaN,NaN,1.01,2020-07-02,705.0
350354,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,146.0,NaN,NaN,NaN,NaN,NaN,NaN,1.01,2020-07-03,711.0
350355,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,149.0,NaN,NaN,NaN,NaN,NaN,NaN,1.01,2020-07-04,718.0
350356,Jamaica,country,<NA>,<NA>,<NA>,Jamaica,2890299.0,18.1155,-77.281,https://github.com/CSSEGISandData/COVID-19,...,149.0,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2020-07-05,718.0